# SPDX-License-Identifier: MIT OR Apache-2.0

# NOTE: DO NOT EDIT MANUALLY!
# NOTE: This file is @generated by the following command:
#
#    $(sl root)/buck/nix/update.sh toolchains
#
# NOTE: Please run the above command to regenerate this file.

nix_toolchains = {
  "bash": {
    "drv": "/nix/store/b328i1rfvvg853wqd5k7fnrr1lvbqxzs-bash-5.1-p16.drv",
    "out": "/nix/store/1azsv2pi1vxb08f4w5xdk4x8gvbzykps-bash-5.1-p16"
  },
  "lua": {
    "drv": "/nix/store/2s1y0w6zaxhky3f70x72yb0jxnjaikf5-lua-5.3.6.drv",
    "out": "/nix/store/qly2l7dai921v6my9r947zrnwpfrks8v-lua-5.3.6"
  },
  "nodejs": {
    "drv": "/nix/store/n0g5ldw65d03r2j1n1jxq02g9k9r2hmn-nodejs-18.12.1.drv",
    "out": "/nix/store/b90dznc25hg8jc3fhjfw9gi40mjb20vh-nodejs-18.12.1"
  },
  "rust-nightly": {
    "drv": "/nix/store/5ww6vl17rsx480lpcanhqc8bcbpsjyr7-rust-default-1.68.0-nightly-2022-12-15.drv",
    "out": "/nix/store/7ci92yd9s3prjjrl4rdhila4vnlmpk5m-rust-default-1.68.0-nightly-2022-12-15"
  },
  "rust-stable": {
    "drv": "/nix/store/fm8rsi9ikanhsjnnnqj7js2032j0d08c-rust-default-1.65.0.drv",
    "out": "/nix/store/b9fkcc9239ra9jn41aihgc60l1p2kxbi-rust-default-1.65.0"
  },
  "tar": {
    "drv": "/nix/store/1ib585m0d2n981072j5ip7dc5pc89139-coreutils-9.1.drv",
    "out": "/nix/store/m79ijrgmx00kf9ka37p6xdyvfgvlj9sh-coreutils-9.1"
  },
  "zip": {
    "drv": "/nix/store/vm54xvgr408dxrspjr31715pzhww57l7-zip-3.0.drv",
    "out": "/nix/store/m2w9dyh6nn6ymi2dzhwmp4xckssi83vg-zip-3.0"
  }
}
