# SPDX-License-Identifier: MIT OR Apache-2.0

# NOTE: DO NOT EDIT MANUALLY!
# NOTE: This file is @generated by the following command:
#
#    $(sl root)/buck/nix/update.sh toolchains
#
# NOTE: Please run the above command to regenerate this file.

nix_toolchains = {
  "tar": {
    "drv": "/nix/store/48wclz4pr6arhjvlwg37v9vhzwq3kr0r-coreutils-9.1.drv",
    "out": "/nix/store/h48pjfgsjl75bm7f3nxcdcrqjkqwns7m-coreutils-9.1"
  },
  "zip": {
    "drv": "/nix/store/9724x1xvxlyhkh3z6hi2icya73g0pln9-zip-3.0.drv",
    "out": "/nix/store/6j50b13mvc0j5vndpfc1jqri3i9vdnyn-zip-3.0"
  }
}
