# SPDX-License-Identifier: MIT OR Apache-2.0

# NOTE: DO NOT EDIT MANUALLY!
# NOTE: This file is @generated by the following command:
#
#    buck run nix//:update -- -t
#
# NOTE: Please run the above command to regenerate this file.

# @nix//toolchains/data.bzl -- nix dependency graph information for buck

# A mapping of all publicly available toolchains for Buck targets to consume,
# keyed by name, with their Nix hash as the value.
toolchains = {
  "bash": "nfgpn9av331q7zi1dl6d5qpir60y513s-bash-5.1-p16",
  "lua": "llva4q6kvzs0y0h0v7lwwi5qxhbsqkv9-lua-5.3.6",
  "nodejs": "nk94ar35r8c86mg6wgqkpil4zgj3cy36-nodejs-18.12.1",
  "rust-nightly": "db84n5ww9ininrlbyx33lbhza1qg2fcc-rust-default-1.68.0-nightly-2022-12-15",
  "rust-stable": "5jfg0xr0nkii0jr7v19ri9zl9fnb8cx8-rust-default-1.65.0",
  "tar": "h48pjfgsjl75bm7f3nxcdcrqjkqwns7m-coreutils-9.1",
  "zip": "6j50b13mvc0j5vndpfc1jqri3i9vdnyn-zip-3.0"
}

# The "shallow" dependency graph of all Nix hashes, keyed by Nix hash, with
# the value being a list of Nix hashes that are referenced by the key.
# This graph is used to download dependencies on-demand when building targets,
# but is not publicly exposed; only 'toolchains' is.
depgraph = {
  "0fv17zk01p08zh6bi17m61zlfh93fcwj-rust-std-1.65.0-x86_64-unknown-linux-gnu": {
    "d": "pnidb991m18kji7dpyiy6g5kzdfz85k6-rust-std-1.65.0-x86_64-unknown-linux-gnu.drv",
    "r": []
  },
  "0r8gq1bq8qlnx5dxd1rbwd2kgf0j63a2-rustfmt-preview-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu": {
    "d": "vz5ijhyzh3xzb5hl3xvr6xrrh9bizv13-rustfmt-preview-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "0v00n26z1q7bpkvs4l8vds6iz7hgbji4-rustc-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu": {
    "d": "mfxy9niikj1ggqp85x0ammphn4h1yzz1-rustc-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "lal84wf8mcz48srgfshj4ns1yadj1acs-zlib-1.2.13",
      "nfgpn9av331q7zi1dl6d5qpir60y513s-bash-5.1-p16"
    ]
  },
  "1b8badwisgx9xmykjzf8vgfh57shf5lc-rust-std-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu": {
    "d": "w7bq1priqvl0skiqbiqw63sqrb04xh43-rust-std-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu.drv",
    "r": []
  },
  "1myi5v5vk83ig4rd6aphzxfcj9jl96ll-xz-5.2.7": {
    "d": "c8xrdbz8hs1qw9wby1czscpyvalffcal-xz-5.2.7.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "2dvg4fgb0lvsvr9i8qlljqj34pk2aydd-rust-docs-1.65.0-x86_64-unknown-linux-gnu": {
    "d": "bdy27gmm7hz4c78psc5csz1fi9ihdbkr-rust-docs-1.65.0-x86_64-unknown-linux-gnu.drv",
    "r": []
  },
  "2s0sp14r5aaxhl0z16b99qcrrpfx7chi-clippy-preview-1.65.0-x86_64-unknown-linux-gnu": {
    "d": "hjm880462ckygsgrybl8gx66ynm06i4z-clippy-preview-1.65.0-x86_64-unknown-linux-gnu.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "wrwx0zy8zblcsq8zwhdqbsxr2jv063fk-rustc-1.65.0-x86_64-unknown-linux-gnu"
    ]
  },
  "2vbw0ga4hlxchc3hfb6443mv735h5gcp-glibc-2.35-163-bin": {
    "d": "633c6jm7lf9j3ybrhycxwavsyvqs6vv7-glibc-2.35-163.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "2vqp383jfrsjb3yq0szzkirya257h1dp-gcc-11.3.0-lib": {
    "d": "qfciv7zdjlakziv6bxjcdnigycjf57yn-gcc-11.3.0.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "3mwc21vzhl9scpphxqsily3qcmy1v20f-mailcap-2.1.53": {
    "d": "5xwgpj7dj4ci2hcrih37v98wha8bsv7f-mailcap-2.1.53.drv",
    "r": []
  },
  "4is4y6n9hxpa19s1f4h6d0bxp2x26i6m-cargo-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu": {
    "d": "pzklqrk1pcq9h0ykzr72wws00k26q1yz-cargo-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "5jfg0xr0nkii0jr7v19ri9zl9fnb8cx8-rust-default-1.65.0": {
    "d": "zycq6ykxk1dvz9fy8d4cnz44g4x690if-rust-default-1.65.0.drv",
    "r": [
      "0fv17zk01p08zh6bi17m61zlfh93fcwj-rust-std-1.65.0-x86_64-unknown-linux-gnu",
      "2dvg4fgb0lvsvr9i8qlljqj34pk2aydd-rust-docs-1.65.0-x86_64-unknown-linux-gnu",
      "2s0sp14r5aaxhl0z16b99qcrrpfx7chi-clippy-preview-1.65.0-x86_64-unknown-linux-gnu",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "k04h29hz6qs45pn0mzaqbyca63lrz2s0-gcc-wrapper-11.3.0",
      "n6mpg42fjx73y2kr1vl8ihj1ykmdhrbm-rustfmt-preview-1.65.0-x86_64-unknown-linux-gnu",
      "wrwx0zy8zblcsq8zwhdqbsxr2jv063fk-rustc-1.65.0-x86_64-unknown-linux-gnu",
      "x7h8sxz1cf5jrx1ixw5am4w300gbrjr1-cargo-1.65.0-x86_64-unknown-linux-gnu"
    ]
  },
  "6b882j01cn2s9xjfsxv44im4pm4b3jsr-acl-2.3.1": {
    "d": "zfyizrab6zvn10gn9nb6nd9ny7m72r7n-acl-2.3.1.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "vv0xndc0ip83f72n0hz0wlcf3g8jhsjd-attr-2.5.1"
    ]
  },
  "6j50b13mvc0j5vndpfc1jqri3i9vdnyn-zip-3.0": {
    "d": "9724x1xvxlyhkh3z6hi2icya73g0pln9-zip-3.0.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "6n6n8apgi368fvxasyicbkv9dw6si350-sqlite-3.40.0": {
    "d": "9a685h256c6d0kl3xs9hdzag4jwspql1-sqlite-3.40.0.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "lal84wf8mcz48srgfshj4ns1yadj1acs-zlib-1.2.13"
    ]
  },
  "7p2s9z3hy317sdwfn0qc5r8qccgynlx1-glibc-2.35-163-dev": {
    "d": "633c6jm7lf9j3ybrhycxwavsyvqs6vv7-glibc-2.35-163.drv",
    "r": [
      "2vbw0ga4hlxchc3hfb6443mv735h5gcp-glibc-2.35-163-bin",
      "dj8gbkmgrkwndjghna8530hxavr7b5f4-linux-headers-6.0",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "92h8cksyz9gycda22dgbvvj2ksm01ca4-binutils-2.39": {
    "d": "jzjzw4gv83cfwqy7gqnk0nsxwmg6qcrq-binutils-2.39.drv",
    "r": [
      "2vqp383jfrsjb3yq0szzkirya257h1dp-gcc-11.3.0-lib",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "lal84wf8mcz48srgfshj4ns1yadj1acs-zlib-1.2.13"
    ]
  },
  "db84n5ww9ininrlbyx33lbhza1qg2fcc-rust-default-1.68.0-nightly-2022-12-15": {
    "d": "4vv66r56ih9hhym0a8gznasbckzc029y-rust-default-1.68.0-nightly-2022-12-15.drv",
    "r": [
      "0r8gq1bq8qlnx5dxd1rbwd2kgf0j63a2-rustfmt-preview-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu",
      "0v00n26z1q7bpkvs4l8vds6iz7hgbji4-rustc-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu",
      "1b8badwisgx9xmykjzf8vgfh57shf5lc-rust-std-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu",
      "4is4y6n9hxpa19s1f4h6d0bxp2x26i6m-cargo-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "i0db9ridw3ad5f674s50c4wnp8rqrmws-rust-docs-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu",
      "iq7iap5imp2y00cjmc3izsi5xqrh2g0g-clippy-preview-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu",
      "k04h29hz6qs45pn0mzaqbyca63lrz2s0-gcc-wrapper-11.3.0"
    ]
  },
  "dj8gbkmgrkwndjghna8530hxavr7b5f4-linux-headers-6.0": {
    "d": "yjhcs5c5v9mc4757fwzdz5d88iqkaj4x-linux-headers-6.0.drv",
    "r": []
  },
  "fnzj8zmxrq96vnigd0zc888qyys22jfv-gnugrep-3.7": {
    "d": "77fvvqprldiac7ic0aaa7i971nbi0gp9-gnugrep-3.7.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "qga0k8h2dk8yszz1p4iz5p1awdq3ng4p-pcre-8.45"
    ]
  },
  "frwb4ki3yl7c4bl7jhxk3h035rx8g158-libxcrypt-4.4.33": {
    "d": "734ly11d2lhqq8q571964ls3j30x6pv4-libxcrypt-4.4.33.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "gc7zr7wh575g1i5zs20lf3g45damwwbs-gcc-11.3.0": {
    "d": "qfciv7zdjlakziv6bxjcdnigycjf57yn-gcc-11.3.0.drv",
    "r": [
      "2vqp383jfrsjb3yq0szzkirya257h1dp-gcc-11.3.0-lib",
      "7p2s9z3hy317sdwfn0qc5r8qccgynlx1-glibc-2.35-163-dev",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "lal84wf8mcz48srgfshj4ns1yadj1acs-zlib-1.2.13"
    ]
  },
  "gljm3f2sy6cdg5ih03haz4bpimh9gna0-openssl-3.0.7-dev": {
    "d": "94xxrx7h5n1j7sqc61i8gfw12lg9ipzp-openssl-3.0.7.drv",
    "r": [
      "h8v9s9cy28dn970iqdi0mkh2dql8w57j-openssl-3.0.7-bin",
      "nh8nnxnbzgmnns9q0s4wxl1274zf323x-openssl-3.0.7"
    ]
  },
  "h48pjfgsjl75bm7f3nxcdcrqjkqwns7m-coreutils-9.1": {
    "d": "48wclz4pr6arhjvlwg37v9vhzwq3kr0r-coreutils-9.1.drv",
    "r": [
      "6b882j01cn2s9xjfsxv44im4pm4b3jsr-acl-2.3.1",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "nwl7pzafadvagabksz61rg3b3cs58n9i-gmp-with-cxx-stage4-6.2.1",
      "vv0xndc0ip83f72n0hz0wlcf3g8jhsjd-attr-2.5.1"
    ]
  },
  "h8v9s9cy28dn970iqdi0mkh2dql8w57j-openssl-3.0.7-bin": {
    "d": "94xxrx7h5n1j7sqc61i8gfw12lg9ipzp-openssl-3.0.7.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "ix8jflc6xha88lhfb33h2l77804i16l8-perl-5.36.0",
      "nh8nnxnbzgmnns9q0s4wxl1274zf323x-openssl-3.0.7"
    ]
  },
  "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163": {
    "d": "633c6jm7lf9j3ybrhycxwavsyvqs6vv7-glibc-2.35-163.drv",
    "r": [
      "s0w6dz5ipv87n7fn808pmzgxa4hq4bil-libidn2-2.3.2"
    ]
  },
  "hz9w5kjpnwia847r4zvnd1dya6viqpz1-binutils-wrapper-2.39": {
    "d": "0ldmqpj7nwkx85q0h0p6vxzfbr2k6mqr-binutils-wrapper-2.39.drv",
    "r": [
      "2vbw0ga4hlxchc3hfb6443mv735h5gcp-glibc-2.35-163-bin",
      "7p2s9z3hy317sdwfn0qc5r8qccgynlx1-glibc-2.35-163-dev",
      "92h8cksyz9gycda22dgbvvj2ksm01ca4-binutils-2.39",
      "h48pjfgsjl75bm7f3nxcdcrqjkqwns7m-coreutils-9.1",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "k0wbm2panqbb0divlapqazbwlvcgv6m0-expand-response-params",
      "nfgpn9av331q7zi1dl6d5qpir60y513s-bash-5.1-p16"
    ]
  },
  "i0db9ridw3ad5f674s50c4wnp8rqrmws-rust-docs-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu": {
    "d": "97jnbnrhcwdb3n8hybq368kivfqpbxs9-rust-docs-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu.drv",
    "r": []
  },
  "in8r0c0ls1hasw582ygi7phk8dr8v95q-libffi-3.4.4": {
    "d": "83qp5c53igb4xa705bfayjr9nv7pv1qv-libffi-3.4.4.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "iq7iap5imp2y00cjmc3izsi5xqrh2g0g-clippy-preview-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu": {
    "d": "dqss6kaz0dpyma61d6dzxgyzqv2b8iql-clippy-preview-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu.drv",
    "r": [
      "0v00n26z1q7bpkvs4l8vds6iz7hgbji4-rustc-1.68.0-nightly-2022-12-15-x86_64-unknown-linux-gnu",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "ix8jflc6xha88lhfb33h2l77804i16l8-perl-5.36.0": {
    "d": "9skbv5abv76d4wiz5vm3in384bg9dlfl-perl-5.36.0.drv",
    "r": [
      "frwb4ki3yl7c4bl7jhxk3h035rx8g158-libxcrypt-4.4.33",
      "h48pjfgsjl75bm7f3nxcdcrqjkqwns7m-coreutils-9.1",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "lal84wf8mcz48srgfshj4ns1yadj1acs-zlib-1.2.13"
    ]
  },
  "iyvphrc2i16bpx8ia6vcz1wz2bvmzkz0-libuv-1.44.2": {
    "d": "9k7myyd41d6px5xzm2rbg2bf62vwzd90-libuv-1.44.2.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "k04h29hz6qs45pn0mzaqbyca63lrz2s0-gcc-wrapper-11.3.0": {
    "d": "7ijnfrb0mzka3y3dixp0ywbvvd54lqfa-gcc-wrapper-11.3.0.drv",
    "r": [
      "2vbw0ga4hlxchc3hfb6443mv735h5gcp-glibc-2.35-163-bin",
      "2vqp383jfrsjb3yq0szzkirya257h1dp-gcc-11.3.0-lib",
      "7p2s9z3hy317sdwfn0qc5r8qccgynlx1-glibc-2.35-163-dev",
      "fnzj8zmxrq96vnigd0zc888qyys22jfv-gnugrep-3.7",
      "gc7zr7wh575g1i5zs20lf3g45damwwbs-gcc-11.3.0",
      "h48pjfgsjl75bm7f3nxcdcrqjkqwns7m-coreutils-9.1",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "hz9w5kjpnwia847r4zvnd1dya6viqpz1-binutils-wrapper-2.39",
      "k0wbm2panqbb0divlapqazbwlvcgv6m0-expand-response-params",
      "nfgpn9av331q7zi1dl6d5qpir60y513s-bash-5.1-p16"
    ]
  },
  "k0wbm2panqbb0divlapqazbwlvcgv6m0-expand-response-params": {
    "d": "1936xz1kbgmbc2176814clsx3r6b5n18-expand-response-params.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "kycg24wmlwhlsdq01nwqmsvkmmq8kb0a-icu4c-72.1-dev": {
    "d": "60b2qqnn9v3yc40g9wp61gbk98s97cya-icu4c-72.1.drv",
    "r": [
      "2vqp383jfrsjb3yq0szzkirya257h1dp-gcc-11.3.0-lib",
      "h48pjfgsjl75bm7f3nxcdcrqjkqwns7m-coreutils-9.1",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "m0x2q5vh6nqddwkhc5f9gqvn1f9ymvfg-icu4c-72.1",
      "nfgpn9av331q7zi1dl6d5qpir60y513s-bash-5.1-p16"
    ]
  },
  "lal84wf8mcz48srgfshj4ns1yadj1acs-zlib-1.2.13": {
    "d": "yrh8fvfhxgz95z3j4rvca9sacj73ab7g-zlib-1.2.13.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "li2r7q4qzmpvgzjiw94899w1zmbh4xl7-readline-6.3p08": {
    "d": "w83dn9nv0f5jqnvm59hb5wikjach384h-readline-6.3p08.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "rngsf0rl2dcdzmyf6j4nxdw3a0i82i6k-ncurses-6.3-p20220507"
    ]
  },
  "llva4q6kvzs0y0h0v7lwwi5qxhbsqkv9-lua-5.3.6": {
    "d": "z7wklfmin8bf2dvspi8sg7ll2g1aqdzj-lua-5.3.6.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "li2r7q4qzmpvgzjiw94899w1zmbh4xl7-readline-6.3p08",
      "rngsf0rl2dcdzmyf6j4nxdw3a0i82i6k-ncurses-6.3-p20220507"
    ]
  },
  "m0x2q5vh6nqddwkhc5f9gqvn1f9ymvfg-icu4c-72.1": {
    "d": "60b2qqnn9v3yc40g9wp61gbk98s97cya-icu4c-72.1.drv",
    "r": [
      "2vqp383jfrsjb3yq0szzkirya257h1dp-gcc-11.3.0-lib",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "nfgpn9av331q7zi1dl6d5qpir60y513s-bash-5.1-p16"
    ]
  },
  "m7wycygp5d02y64dk92p88ac7x92pzjd-openssl-3.0.7": {
    "d": "6apmr6f3z8pq7i2v9zy4q2x6jaddj4d0-openssl-3.0.7.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "mmv7blsljgjvm67yh3filz84bx39i28s-tzdata-2022f": {
    "d": "1m4s0gy8ka1pqf9p7721shdc0mzymhjr-tzdata-2022f.drv",
    "r": []
  },
  "n6mpg42fjx73y2kr1vl8ihj1ykmdhrbm-rustfmt-preview-1.65.0-x86_64-unknown-linux-gnu": {
    "d": "m4yzz8g1wlgjcw8g1yvx5i13m6afnvpl-rustfmt-preview-1.65.0-x86_64-unknown-linux-gnu.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "nfgpn9av331q7zi1dl6d5qpir60y513s-bash-5.1-p16": {
    "d": "96a6khgp0qym18kd759wwcnkhwvbpzg4-bash-5.1-p16.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "nh8nnxnbzgmnns9q0s4wxl1274zf323x-openssl-3.0.7": {
    "d": "94xxrx7h5n1j7sqc61i8gfw12lg9ipzp-openssl-3.0.7.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "nk94ar35r8c86mg6wgqkpil4zgj3cy36-nodejs-18.12.1": {
    "d": "b0dmns47qx627wk4wyyqjaqzmm44krcl-nodejs-18.12.1.drv",
    "r": [
      "2vqp383jfrsjb3yq0szzkirya257h1dp-gcc-11.3.0-lib",
      "gljm3f2sy6cdg5ih03haz4bpimh9gna0-openssl-3.0.7-dev",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "iyvphrc2i16bpx8ia6vcz1wz2bvmzkz0-libuv-1.44.2",
      "kycg24wmlwhlsdq01nwqmsvkmmq8kb0a-icu4c-72.1-dev",
      "lal84wf8mcz48srgfshj4ns1yadj1acs-zlib-1.2.13",
      "m0x2q5vh6nqddwkhc5f9gqvn1f9ymvfg-icu4c-72.1",
      "nfgpn9av331q7zi1dl6d5qpir60y513s-bash-5.1-p16",
      "nh8nnxnbzgmnns9q0s4wxl1274zf323x-openssl-3.0.7",
      "nzgqxw4d875pgl1lji8n3q82x3bf7ldi-python3-3.10.8",
      "v4gn0w3rg3ci8mi5bzlsj3ls6hnm804i-zlib-1.2.13-dev"
    ]
  },
  "nwl7pzafadvagabksz61rg3b3cs58n9i-gmp-with-cxx-stage4-6.2.1": {
    "d": "5l7czx0m2x72i9dsnxn7dgf5vfd7a6n0-gmp-with-cxx-stage4-6.2.1.drv",
    "r": [
      "2vqp383jfrsjb3yq0szzkirya257h1dp-gcc-11.3.0-lib",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "nzgqxw4d875pgl1lji8n3q82x3bf7ldi-python3-3.10.8": {
    "d": "r4cn4z1481jr5l8zjbjy7s568d1jn5mr-python3-3.10.8.drv",
    "r": [
      "1myi5v5vk83ig4rd6aphzxfcj9jl96ll-xz-5.2.7",
      "3mwc21vzhl9scpphxqsily3qcmy1v20f-mailcap-2.1.53",
      "6n6n8apgi368fvxasyicbkv9dw6si350-sqlite-3.40.0",
      "frwb4ki3yl7c4bl7jhxk3h035rx8g158-libxcrypt-4.4.33",
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "in8r0c0ls1hasw582ygi7phk8dr8v95q-libffi-3.4.4",
      "lal84wf8mcz48srgfshj4ns1yadj1acs-zlib-1.2.13",
      "li2r7q4qzmpvgzjiw94899w1zmbh4xl7-readline-6.3p08",
      "m7wycygp5d02y64dk92p88ac7x92pzjd-openssl-3.0.7",
      "mmv7blsljgjvm67yh3filz84bx39i28s-tzdata-2022f",
      "nfgpn9av331q7zi1dl6d5qpir60y513s-bash-5.1-p16",
      "pgidzv3llcvjsr4f5g8hwaf9nc091b1h-gdbm-1.23",
      "rngsf0rl2dcdzmyf6j4nxdw3a0i82i6k-ncurses-6.3-p20220507",
      "x1r7dm76fv9lm5w675k5j6mvgzdj62im-expat-2.5.0",
      "xc4my8bxg9955fp80v8m58y9cl5r66gf-bzip2-1.0.8"
    ]
  },
  "pgidzv3llcvjsr4f5g8hwaf9nc091b1h-gdbm-1.23": {
    "d": "v6fsz8180l3yn1a0gx6si0wfzbz3zssd-gdbm-1.23.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "qga0k8h2dk8yszz1p4iz5p1awdq3ng4p-pcre-8.45": {
    "d": "6mwbd8nvz9gd2aw4cql0q66hdh7yhn9p-pcre-8.45.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "rngsf0rl2dcdzmyf6j4nxdw3a0i82i6k-ncurses-6.3-p20220507": {
    "d": "rqh2mqnfchr3d19gw3r371n1mwqd6di6-ncurses-6.3-p20220507.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "s0w6dz5ipv87n7fn808pmzgxa4hq4bil-libidn2-2.3.2": {
    "d": "jk3rdvzkpy5bi6niw06isxix8a8yyz5h-libidn2-2.3.2.drv",
    "r": [
      "sdsqayp3k5w5hqraa3bkp1bys613q7dc-libunistring-1.0"
    ]
  },
  "sdsqayp3k5w5hqraa3bkp1bys613q7dc-libunistring-1.0": {
    "d": "pxgy30jiklxjcf3nnpf7n3q3gi7qhcva-libunistring-1.0.drv",
    "r": []
  },
  "v4gn0w3rg3ci8mi5bzlsj3ls6hnm804i-zlib-1.2.13-dev": {
    "d": "yrh8fvfhxgz95z3j4rvca9sacj73ab7g-zlib-1.2.13.drv",
    "r": [
      "lal84wf8mcz48srgfshj4ns1yadj1acs-zlib-1.2.13"
    ]
  },
  "vv0xndc0ip83f72n0hz0wlcf3g8jhsjd-attr-2.5.1": {
    "d": "y8jqh6zb1nlpj0s5bvjhqp9r9fwxbizs-attr-2.5.1.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "wrwx0zy8zblcsq8zwhdqbsxr2jv063fk-rustc-1.65.0-x86_64-unknown-linux-gnu": {
    "d": "pbzngzhd0y31syvlai7hf7i3cyskq75h-rustc-1.65.0-x86_64-unknown-linux-gnu.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163",
      "lal84wf8mcz48srgfshj4ns1yadj1acs-zlib-1.2.13",
      "nfgpn9av331q7zi1dl6d5qpir60y513s-bash-5.1-p16"
    ]
  },
  "x1r7dm76fv9lm5w675k5j6mvgzdj62im-expat-2.5.0": {
    "d": "shnmgrk4rkd9bx43plflpk440r7xfdi9-expat-2.5.0.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "x7h8sxz1cf5jrx1ixw5am4w300gbrjr1-cargo-1.65.0-x86_64-unknown-linux-gnu": {
    "d": "4kz54zz3ilwqdka1av9zy005wnd3q03v-cargo-1.65.0-x86_64-unknown-linux-gnu.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  },
  "xc4my8bxg9955fp80v8m58y9cl5r66gf-bzip2-1.0.8": {
    "d": "sm11a6h3l9dryqdpnr0f9phbxq800jmx-bzip2-1.0.8.drv",
    "r": [
      "hsk71z8admvgykn7vzjy11dfnar9f4r1-glibc-2.35-163"
    ]
  }
}
